language: node_js
sudo: false
env:
  global:
    - secure: igEl4GdexOBIZvIRBXGxwIJMYbU36hXWKhUcoqEAFlJaY/EvywgnxUxCDhDaudkvTHFpuaSKb23Qo7tG2e9bQgdpI/JwlOtpLSDRQcp3misF7xxG14y8ZSiu/xnEWS2dccN6MfXrf6T3GwM5StkKD9qjKJL/vvwi8V/b08OpNcQ=
node_js:
  - "0.12"
  - "iojs"
  - "4.1"
before_script:
  - "cp config/config_sample.js config/config.js"
  - npm install -g codeclimate-test-reporter
after_script:
  - ./node_modules/.bin/mocha -R mocha-lcov-reporter > lcov.info
  - cat lcov.info | codeclimate-test-reporter
